### ISSUE TITLE
/bondconnections/HASH returns empty list

### ISSUE THREAD

**Issue by michi7x7** [JuliaPluto/PlutoBindServer.jl#1]
Looking at our [testcase](https://captain-bayes.github.io/bayes-imoox/notebooks/test_multi_bind.html), the bond connections reported on the JS console is an empty array: `Bond connections: {}`
From my understanding, this causes our sliders to not update all of the affected cells.

The front-end JS (`editor.bundle.js`) and static export uses Pluto.jl@d9a3466 and PlutoUtils.js@e36c984. The bind server is PlutoBindServer.jl@01836ca and loads the same Pluto.jl and PlutoUtils.js.

The complete setup+notebookfiles can be found here: https://github.com/Captain-Bayes/bayes-imoox, the setup is heavily based on the computationalthinking course.

We have little experience in debugging julia code, so I would appreciate some hints on how to debug `bound_variable_connections_graph` and ultimately `notebook.topology` in the context of PlutoBindServer.jl.

@dorn-gerhard

**Comment by fonsp** [comment]
Hi @michi7x7,

Thanks for you report! Do I remember correctly that you also sent this on another platform? If so, sorry that I forgot to reply.

I found this bug too, it seems to occur when you define bonds inside a markdown interpolation, e.g.
```julia
md"""
Hello $(@bind world html"<input value=world>")
"""
```

It looks like this is also the case with your notebook.

I already started working on a fix, it should be released within a week! In the meantime, you can rewrite your cell to:
```julia
begin
local bond = @bind world html"<input value=world>"
md"""
Hello $(bond)
"""
end
```

Also, I would love to meet! Maybe we can set up a video call? fons@mit.edu

**Comment by fonsp** [comment]
It's fixed, see this commit for the new Pluto and PlutoBindServer versions (they need to be exactly this):
https://github.com/mitmath/18S191/commit/6d4aa2f749f2a1689189e5c81d8b3c26fdd3459e

**Comment by fonsp** [comment]
I added it as test case: https://github.com/JuliaPluto/PlutoBindServer.jl/blob/cc64e0818c7d2179eb13489ecff1777b67b757e1/test/parallelpaths4.jl#L168-L173

**Comment by fonsp** [comment]
You may need to clear your cache for this fix to take effect

**Comment by dorn-gerhard** [comment]
Works perfectly now 👍 
Thank you :)
(tested it already on our example notebook:
https://captain-bayes.github.io/bayes-imoox/notebooks/test_multi_bind.html)

**Comment by dorn-gerhard** [comment]
@fonsp 
A meeting / video call would be awesome, I've sent you a mail
